// Produktkatalog – Daten und Fotos basieren auf den Herstellerangaben (kukirin.it.com).
// Alle Werte sind Herstellerangaben ("bis zu"); vor Livegang Preise, Lieferumfang und
// Zulassungsstatus mit dem Großhändler/Hersteller abgleichen.
//
// tags:  abe | sitz | power | budget
// cmp:   Werte für die Vergleichstabelle ("–" = vom Hersteller nicht angegeben)
const NO_ABE = "Keine deutsche ABE – nur für Privatgelände";

const PRODUCTS = [
  {
    id: "g2-pro-abe",
    name: "Kukirin G2 Pro ABE",
    tagline: "Legal auf deutschen Straßen",
    price: 499,
    tags: ["abe", "budget"],
    badge: "ABE · Straßenzulassung",
    featured: true,
    images: 7,
    desc: "Die Version des G2 Pro mit ABE für den Einsatz im deutschen Straßenverkehr: auf 20 km/h ausgelegt, mit Scheibenbremsen, Licht und klappbarem Design für Bahn und Büro.",
    highlights: [
      "ABE – für öffentliche Straßen geeignet (max. 20 km/h)",
      "Scheibenbremsen vorn und hinten",
      "Klappbar für Transport und Lagerung",
      "Beleuchtung vorn und hinten",
    ],
    cmp: { motor: "–", akku: "–", speed: "20 km/h", range: "–", tire: "9\"" },
    specs: {
      "Straßenzulassung": "ABE (max. 20 km/h)",
      "Reifen": "9\"",
      "Bremsen": "Scheibenbremsen",
      "Klappbar": "Ja",
    },
  },
  {
    id: "g2-pro",
    name: "Kukirin G2 Pro",
    tagline: "Mit abnehmbarem Sitz",
    price: 499,
    tags: ["sitz", "budget"],
    images: 6,
    desc: "Wechsle mit einem Handgriff zwischen Stehen und Sitzen. Der 600-W-Motor beschleunigt souverän, die 9-Zoll-Offroad-Reifen schlucken Unebenheiten, und das 6-Licht-System sorgt für Sichtbarkeit bei Nacht.",
    highlights: [
      "Abnehmbarer Sitz für lange Strecken",
      "Höhenverstellbare Teleskopstange",
      "6-Licht-System inkl. Blinker und Bremslicht",
      "Schnell-Faltmechanismus",
    ],
    cmp: { motor: "600 W", akku: "15,6 Ah", speed: "–", range: "–", tire: "9\"" },
    specs: {
      "Motor": "600 W bürstenlos",
      "Akku": "15,6 Ah Lithium",
      "Reifen": "9\" Offroad-Vakuumreifen",
      "Bremsen": "Scheibenbremsen vorn + hinten",
      "Beleuchtung": "6-Licht-System",
      "Display": "LED-Display",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g2",
    name: "Kukirin G2",
    tagline: "800 W, Touchdisplay, 45 km/h",
    price: 489,
    tags: ["budget"],
    images: 7,
    desc: "Starker 800-W-Nabenmotor mit sanfter Sinus-Beschleunigung, drei Fahrstufen und Touchdisplay. Mit rund 26 kg bleibt der G2 gut tragbar und trotzdem für Gelände gebaut.",
    highlights: [
      "3 Fahrstufen von Eco (15 km/h) bis 45 km/h",
      "Touchdisplay mit Fahrdaten",
      "Federung vorn und hinten",
      "7-Licht-System mit Ambientelicht",
    ],
    cmp: { motor: "800 W", akku: "48 V / 15 Ah", speed: "45 km/h", range: "55 km", tire: "10\"" },
    specs: {
      "Motor": "800 W Nabenmotor",
      "Akku": "48 V / 15 Ah",
      "Höchstgeschwindigkeit": "45 km/h",
      "Reichweite": "bis 55 km (bei 65 kg Last)",
      "Reifen": "10\" Offroad-Vakuumreifen",
      "Bremsen": "Scheibenbremsen vorn + hinten, E-Bremse",
      "Gewicht": "ca. 26 kg",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g2-max",
    name: "Kukirin G2 Max",
    tagline: "1.000 W und 70 km Reichweite",
    price: 649,
    tags: ["sitz"],
    badge: "Mit Sitz",
    images: 8,
    desc: "Großer 48-V-Akku, 1.000-W-Motor und ein bequemer abnehmbarer Sitz: Der G2 Max ist der Langstrecken-Komfortler der G2-Familie und nimmt Steigungen bis 22°.",
    highlights: [
      "Bis zu 70 km Reichweite",
      "Steigungen bis 22°",
      "Dreistufig verstellbare Teleskopstange",
      "Abnehmbarer Sitz mit dickem Polster",
    ],
    cmp: { motor: "1.000 W", akku: "48 V / 20,8 Ah", speed: "–", range: "70 km", tire: "10\"" },
    specs: {
      "Motor": "1.000 W",
      "Akku": "48 V / 20,8 Ah",
      "Reichweite": "bis 70 km",
      "Steigfähigkeit": "bis 22°",
      "Reifen": "10\" Offroad-Reifen",
      "Federung": "Feder-Dämpfer",
      "Beleuchtung": "6-LED-System",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g2-master",
    name: "Kukirin G2 Master",
    tagline: "Dual-Motor mit 60 km/h",
    price: 839,
    tags: ["power"],
    images: 8,
    desc: "Zwei 1.000-W-Motoren, 52-V-Akku und hydraulische Federung vorn und hinten: Der G2 Master beschleunigt brachial, klettert Steigungen bis 28° und bremst mit Doppelscheibe plus E-Bremse.",
    highlights: [
      "2 × 1.000 W (2.000 W gesamt)",
      "Hydraulische Federung vorn und hinten",
      "Bremsweg 6–12 m dank Scheibenbremsen + E-Bremse",
      "8-Licht-System",
    ],
    cmp: { motor: "2 × 1.000 W", akku: "52 V / 20,8 Ah", speed: "60 km/h", range: "70 km", tire: "–" },
    specs: {
      "Motor": "2 × 1.000 W (Dual)",
      "Akku": "52 V / 20,8 Ah",
      "Höchstgeschwindigkeit": "60 km/h",
      "Reichweite": "bis 70 km",
      "Steigfähigkeit": "bis 28°",
      "Federung": "Hydraulisch vorn + hinten",
      "Bremsen": "Scheibenbremsen vorn + hinten + E-Bremse",
      "Rahmen": "Aluminiumlegierung",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g3-pro",
    name: "Kukirin G3 Pro",
    tagline: "Dual 1.200 W, Wechsel-Akku",
    price: 1259,
    tags: ["power"],
    badge: "Top Reichweite",
    featured: true,
    images: 8,
    desc: "Der G3 Pro vereint zwei 1.200-W-Motoren mit einem abnehmbaren 23,4-Ah-Akku und bis zu 80 km Reichweite. Zwei Ladeports laden den Akku mit zwei Ladegeräten gleichzeitig – für kurze Pausen an der Steckdose.",
    highlights: [
      "Bis zu 65 km/h und 80 km Reichweite",
      "Abnehmbarer Akku zum Laden drinnen",
      "Zwei Ladeports für Schnellladen",
      "Federung vorn und hinten",
    ],
    cmp: { motor: "2 × 1.200 W", akku: "52 V / 23,4 Ah", speed: "65 km/h", range: "80 km", tire: "10\"" },
    specs: {
      "Motor": "2 × 1.200 W (Dual)",
      "Akku": "52 V / 23,4 Ah, abnehmbar",
      "Höchstgeschwindigkeit": "65 km/h",
      "Reichweite": "bis 80 km",
      "Reifen": "10\" Offroad-Reifen",
      "Federung": "Dual-Stoßdämpfer vorn + hinten",
      "Laden": "2 Ladeports",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g4",
    name: "Kukirin G4",
    tagline: "2.000 W, 70 km/h, 11\" Reifen",
    price: 859,
    tags: ["power"],
    badge: "Performance",
    featured: true,
    images: 8,
    desc: "Das Hochleistungs-Modell mit 2.000-W-Nabenmotor, doppelt gekühlt, 20-Ah-Akku (1.200 Wh) und extrabreiten 11-Zoll-Vakuumreifen. Hohler Rahmen, Touchscreen und LED-Lichtsystem inklusive.",
    highlights: [
      "2.000-W-Nabenmotor mit Dual-Kühlung",
      "Bis zu 70 km/h, bis 75 km Reichweite",
      "11\" Breitreifen für Sand, Schnee und Trails",
      "Touchscreen-Display",
    ],
    cmp: { motor: "2.000 W", akku: "20 Ah / 1.200 Wh", speed: "70 km/h", range: "75 km", tire: "11\"" },
    specs: {
      "Motor": "2.000 W Nabenmotor",
      "Akku": "20 Ah (1.200 Wh)",
      "Höchstgeschwindigkeit": "70 km/h",
      "Reichweite": "bis 75 km",
      "Reifen": "11\" Breitreifen (Vakuum)",
      "Rahmen": "Stahl-Aluminium-Legierung",
      "Display": "Touchscreen",
      "Beleuchtung": "6-LED-System",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "m4-max",
    name: "Kukirin M4 Max",
    tagline: "800 W Allrounder im Industrial-Look",
    price: 469,
    tags: ["budget"],
    images: 8,
    desc: "Der M4 Max bringt den beliebten Gashebel der M4-Serie mit 800 W, 48-V/18-Ah-Akku und schlauchlosen 10-Zoll-Reifen. Doppelgabel vorn und Rotfedern hinten sorgen für Ruhe auf schlechtem Belag.",
    highlights: [
      "800 W, bis 45 km/h, bis 64 km",
      "Schlauchlose 10\" Reifen – pannensicher",
      "Doppelgabel + Federn hinten",
      "Ambientebeleuchtung und Blinker",
    ],
    cmp: { motor: "800 W", akku: "48 V / 18 Ah", speed: "45 km/h", range: "64 km", tire: "10\"" },
    specs: {
      "Motor": "800 W bürstenlos",
      "Akku": "48 V / 18 Ah",
      "Höchstgeschwindigkeit": "45 km/h",
      "Reichweite": "bis 64 km",
      "Reifen": "10\" schlauchlos",
      "Federung": "Doppelgabel vorn, Federn hinten",
      "Beleuchtung": "Ambientelicht, Scheinwerfer, Rücklicht, Blinker",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "s1-max",
    name: "Kukirin S1 Max",
    tagline: "Leicht, kompakt, günstig",
    price: 249,
    tags: ["budget"],
    badge: "Einstieg",
    images: 8,
    desc: "Mit nur 16 kg ist der S1 Max der handliche Stadtbegleiter: Einhand-Faltmechanismus, 350-W-Motor und bis zu 39 km Reichweite für Campus, Büro und den Weg zur Bahn.",
    highlights: [
      "Nur 16 kg – leicht zu tragen",
      "Faltung per Knopfdruck",
      "Bis zu 39 km Reichweite",
      "Der günstigste Einstieg in die Kukirin-Welt",
    ],
    cmp: { motor: "350 W", akku: "36 V / 10,4 Ah", speed: "25 km/h", range: "39 km", tire: "–" },
    specs: {
      "Motor": "350 W",
      "Akku": "36 V / 10,4 Ah",
      "Höchstgeschwindigkeit": "25 km/h",
      "Reichweite": "bis 39 km",
      "Gewicht": "16 kg",
      "Klappbar": "Ja, Ein-Knopf-Faltung",
      "Straßenzulassung": NO_ABE,
    },
  },
];

// Bilddateien: img/<id>-1.jpg … img/<id>-N.jpg
PRODUCTS.forEach((p) => {
  p.gallery = Array.from({ length: p.images }, (_, i) => `img/${p.id}-${i + 1}.jpg`);
});
