// Produktkatalog – Daten und Fotos basieren auf den Herstellerangaben (kukirin.it.com).
// Alle Werte sind Herstellerangaben ("bis zu"); vor Livegang Preise, Lieferumfang und
// Zulassungsstatus mit dem Großhändler/Hersteller abgleichen.
//
// tags:  abe | sitz | power | budget
// cmp:   Werte für die Vergleichstabelle ("–" = vom Hersteller nicht angegeben)
const NO_ABE = "Keine deutsche ABE – nur für Privatgelände";

const PRODUCTS = [
  {
    id: "g2-pro-abe",
    name: "Kukirin G2 Pro ABE",
    tagline: "Legal auf deutschen Straßen",
    price: 499,
    tags: ["abe", "budget"],
    badge: "ABE · Straßenzulassung",
    featured: true,
    images: 7,
    desc: "Die Version des G2 Pro mit ABE für den Einsatz im deutschen Straßenverkehr: auf 20 km/h ausgelegt, mit Scheibenbremsen, Licht und klappbarem Design für Bahn und Büro.",
    highlights: [
      "ABE – für öffentliche Straßen geeignet (max. 20 km/h)",
      "Scheibenbremsen vorn und hinten",
      "Klappbar für Transport und Lagerung",
      "Beleuchtung vorn und hinten",
    ],
    cmp: { motor: "–", akku: "–", speed: "20 km/h", range: "–", tire: "9\"" },
    specs: {
      "Straßenzulassung": "ABE (max. 20 km/h)",
      "Reifen": "9\"",
      "Bremsen": "Scheibenbremsen",
      "Klappbar": "Ja",
    },
  },
  {
    id: "g2-pro",
    name: "Kukirin G2 Pro",
    tagline: "Mit abnehmbarem Sitz",
    price: 499,
    tags: ["sitz", "budget"],
    images: 6,
    desc: "Wechsle mit einem Handgriff zwischen Stehen und Sitzen. Der 600-W-Motor beschleunigt souverän, die 9-Zoll-Offroad-Reifen schlucken Unebenheiten, und das 6-Licht-System sorgt für Sichtbarkeit bei Nacht.",
    highlights: [
      "Abnehmbarer Sitz für lange Strecken",
      "Höhenverstellbare Teleskopstange",
      "6-Licht-System inkl. Blinker und Bremslicht",
      "Schnell-Faltmechanismus",
    ],
    cmp: { motor: "600 W", akku: "15,6 Ah", speed: "–", range: "–", tire: "9\"" },
    specs: {
      "Motor": "600 W bürstenlos",
      "Akku": "15,6 Ah Lithium",
      "Reifen": "9\" Offroad-Vakuumreifen",
      "Bremsen": "Scheibenbremsen vorn + hinten",
      "Beleuchtung": "6-Licht-System",
      "Display": "LED-Display",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g2",
    name: "Kukirin G2",
    tagline: "800 W, Touchdisplay, 45 km/h",
    price: 489,
    tags: ["budget"],
    images: 7,
    desc: "Starker 800-W-Nabenmotor mit sanfter Sinus-Beschleunigung, drei Fahrstufen und Touchdisplay. Mit rund 26 kg bleibt der G2 gut tragbar und trotzdem für Gelände gebaut.",
    highlights: [
      "3 Fahrstufen von Eco (15 km/h) bis 45 km/h",
      "Touchdisplay mit Fahrdaten",
      "Federung vorn und hinten",
      "7-Licht-System mit Ambientelicht",
    ],
    cmp: { motor: "800 W", akku: "48 V / 15 Ah", speed: "45 km/h", range: "55 km", tire: "10\"" },
    specs: {
      "Motor": "800 W Nabenmotor",
      "Akku": "48 V / 15 Ah",
      "Höchstgeschwindigkeit": "45 km/h",
      "Reichweite": "bis 55 km (bei 65 kg Last)",
      "Reifen": "10\" Offroad-Vakuumreifen",
      "Bremsen": "Scheibenbremsen vorn + hinten, E-Bremse",
      "Gewicht": "ca. 26 kg",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g2-max",
    name: "Kukirin G2 Max",
    tagline: "1.000 W und 70 km Reichweite",
    price: 649,
    tags: ["sitz"],
    badge: "Mit Sitz",
    images: 8,
    desc: "Großer 48-V-Akku, 1.000-W-Motor und ein bequemer abnehmbarer Sitz: Der G2 Max ist der Langstrecken-Komfortler der G2-Familie und nimmt Steigungen bis 22°.",
    highlights: [
      "Bis zu 70 km Reichweite",
      "Steigungen bis 22°",
      "Dreistufig verstellbare Teleskopstange",
      "Abnehmbarer Sitz mit dickem Polster",
    ],
    cmp: { motor: "1.000 W", akku: "48 V / 20,8 Ah", speed: "–", range: "70 km", tire: "10\"" },
    specs: {
      "Motor": "1.000 W",
      "Akku": "48 V / 20,8 Ah",
      "Reichweite": "bis 70 km",
      "Steigfähigkeit": "bis 22°",
      "Reifen": "10\" Offroad-Reifen",
      "Federung": "Feder-Dämpfer",
      "Beleuchtung": "6-LED-System",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g2-master",
    name: "Kukirin G2 Master",
    tagline: "Dual-Motor mit 60 km/h",
    price: 839,
    tags: ["power"],
    images: 8,
    desc: "Zwei 1.000-W-Motoren, 52-V-Akku und hydraulische Federung vorn und hinten: Der G2 Master beschleunigt brachial, klettert Steigungen bis 28° und bremst mit Doppelscheibe plus E-Bremse.",
    highlights: [
      "2 × 1.000 W (2.000 W gesamt)",
      "Hydraulische Federung vorn und hinten",
      "Bremsweg 6–12 m dank Scheibenbremsen + E-Bremse",
      "8-Licht-System",
    ],
    cmp: { motor: "2 × 1.000 W", akku: "52 V / 20,8 Ah", speed: "60 km/h", range: "70 km", tire: "–" },
    specs: {
      "Motor": "2 × 1.000 W (Dual)",
      "Akku": "52 V / 20,8 Ah",
      "Höchstgeschwindigkeit": "60 km/h",
      "Reichweite": "bis 70 km",
      "Steigfähigkeit": "bis 28°",
      "Federung": "Hydraulisch vorn + hinten",
      "Bremsen": "Scheibenbremsen vorn + hinten + E-Bremse",
      "Rahmen": "Aluminiumlegierung",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g3-pro",
    name: "Kukirin G3 Pro",
    tagline: "Dual 1.200 W, Wechsel-Akku",
    price: 1259,
    tags: ["power"],
    badge: "Top Reichweite",
    featured: true,
    images: 8,
    desc: "Der G3 Pro vereint zwei 1.200-W-Motoren mit einem abnehmbaren 23,4-Ah-Akku und bis zu 80 km Reichweite. Zwei Ladeports laden den Akku mit zwei Ladegeräten gleichzeitig – für kurze Pausen an der Steckdose.",
    highlights: [
      "Bis zu 65 km/h und 80 km Reichweite",
      "Abnehmbarer Akku zum Laden drinnen",
      "Zwei Ladeports für Schnellladen",
      "Federung vorn und hinten",
    ],
    cmp: { motor: "2 × 1.200 W", akku: "52 V / 23,4 Ah", speed: "65 km/h", range: "80 km", tire: "10\"" },
    specs: {
      "Motor": "2 × 1.200 W (Dual)",
      "Akku": "52 V / 23,4 Ah, abnehmbar",
      "Höchstgeschwindigkeit": "65 km/h",
      "Reichweite": "bis 80 km",
      "Reifen": "10\" Offroad-Reifen",
      "Federung": "Dual-Stoßdämpfer vorn + hinten",
      "Laden": "2 Ladeports",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "g4",
    name: "Kukirin G4",
    tagline: "2.000 W, 70 km/h, 11\" Reifen",
    price: 859,
    tags: ["power"],
    badge: "Performance",
    featured: true,
    images: 8,
    desc: "Das Hochleistungs-Modell mit 2.000-W-Nabenmotor, doppelt gekühlt, 20-Ah-Akku (1.200 Wh) und extrabreiten 11-Zoll-Vakuumreifen. Hohler Rahmen, Touchscreen und LED-Lichtsystem inklusive.",
    highlights: [
      "2.000-W-Nabenmotor mit Dual-Kühlung",
      "Bis zu 70 km/h, bis 75 km Reichweite",
      "11\" Breitreifen für Sand, Schnee und Trails",
      "Touchscreen-Display",
    ],
    cmp: { motor: "2.000 W", akku: "20 Ah / 1.200 Wh", speed: "70 km/h", range: "75 km", tire: "11\"" },
    specs: {
      "Motor": "2.000 W Nabenmotor",
      "Akku": "20 Ah (1.200 Wh)",
      "Höchstgeschwindigkeit": "70 km/h",
      "Reichweite": "bis 75 km",
      "Reifen": "11\" Breitreifen (Vakuum)",
      "Rahmen": "Stahl-Aluminium-Legierung",
      "Display": "Touchscreen",
      "Beleuchtung": "6-LED-System",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "m4-max",
    name: "Kukirin M4 Max",
    tagline: "800 W Allrounder im Industrial-Look",
    price: 469,
    tags: ["budget"],
    images: 8,
    desc: "Der M4 Max bringt den beliebten Gashebel der M4-Serie mit 800 W, 48-V/18-Ah-Akku und schlauchlosen 10-Zoll-Reifen. Doppelgabel vorn und Rotfedern hinten sorgen für Ruhe auf schlechtem Belag.",
    highlights: [
      "800 W, bis 45 km/h, bis 64 km",
      "Schlauchlose 10\" Reifen – pannensicher",
      "Doppelgabel + Federn hinten",
      "Ambientebeleuchtung und Blinker",
    ],
    cmp: { motor: "800 W", akku: "48 V / 18 Ah", speed: "45 km/h", range: "64 km", tire: "10\"" },
    specs: {
      "Motor": "800 W bürstenlos",
      "Akku": "48 V / 18 Ah",
      "Höchstgeschwindigkeit": "45 km/h",
      "Reichweite": "bis 64 km",
      "Reifen": "10\" schlauchlos",
      "Federung": "Doppelgabel vorn, Federn hinten",
      "Beleuchtung": "Ambientelicht, Scheinwerfer, Rücklicht, Blinker",
      "Straßenzulassung": NO_ABE,
    },
  },
  {
    id: "s1-max",
    name: "Kukirin S1 Max",
    tagline: "Leicht, kompakt, günstig",
    price: 249,
    tags: ["budget"],
    badge: "Einstieg",
    images: 8,
    desc: "Mit nur 16 kg ist der S1 Max der handliche Stadtbegleiter: Einhand-Faltmechanismus, 350-W-Motor und bis zu 39 km Reichweite für Campus, Büro und den Weg zur Bahn.",
    highlights: [
      "Nur 16 kg – leicht zu tragen",
      "Faltung per Knopfdruck",
      "Bis zu 39 km Reichweite",
      "Der günstigste Einstieg in die Kukirin-Welt",
    ],
    cmp: { motor: "350 W", akku: "36 V / 10,4 Ah", speed: "25 km/h", range: "39 km", tire: "–" },
    specs: {
      "Motor": "350 W",
      "Akku": "36 V / 10,4 Ah",
      "Höchstgeschwindigkeit": "25 km/h",
      "Reichweite": "bis 39 km",
      "Gewicht": "16 kg",
      "Klappbar": "Ja, Ein-Knopf-Faltung",
      "Straßenzulassung": NO_ABE,
    },
  },
];

// Scooter: Bilddateien img/<id>-1.jpg … img/<id>-N.jpg
PRODUCTS.forEach((p) => {
  p.cat = "scooter";
  p.gallery = Array.from({ length: p.images }, (_, i) => `img/${p.id}-${i + 1}.jpg`);
});

// ====== Taschen & Merch ======
// ACHTUNG: Das sind Shop-eigene BEISPIEL-Artikel (Hersteller Kukirin führt weder Taschen noch Merch).
// Preise, Maße, Materialien und die Produktgrafiken (img/*.svg) sind Platzhalter – vor Livegang durch
// die Daten und Fotos deines Lieferanten ersetzen. Die Marke "Kukirin" nur mit Erlaubnis auf Merch drucken.
// sizes/colors: erzeugen eine Auswahl im Produktdialog. colors[].i = Index des passenden Bildes.
const SIZES = ["S", "M", "L", "XL", "XXL"];
const EXTRA = [
  {
    id: "tasche-lenker", cat: "tasche", name: "Lenkertasche 2 L", tagline: "Handy & Schlüssel griffbereit",
    price: 24.9, meta: ["2 Liter", "Wasserabweisend"], badge: "Beliebt", featured: true,
    files: ["tasche-lenker-1.svg", "tasche-lenker-2.svg"],
    desc: "Kompakte Tasche für die Lenkerstange: Platz für Smartphone, Schlüssel und Geldbeutel, immer in Reichweite. Mit Hauptfach und Vordertasche, beides mit Reißverschluss.",
    highlights: ["Hauptfach + Vordertasche mit Reißverschluss", "Befestigung per Schnallenbändern", "Wasserabweisendes Material"],
    specs: { "Volumen": "ca. 2 Liter", "Material": "Polyester, wasserabweisend", "Befestigung": "Schnallenbänder am Lenker", "Farbe": "Schwarz / Orange" },
    note: "Bitte prüfe vor dem Kauf, ob die Tasche zu Lenker und Display deines Scooters passt.",
  },
  {
    id: "tasche-transport", cat: "tasche", name: "Transporttasche XL", tagline: "Scooter sicher verstauen & tragen",
    price: 59.9, meta: ["XL", "Gepolstert"],
    files: ["tasche-transport-1.svg", "tasche-transport-2.svg"],
    desc: "Große, gepolsterte Tasche für gefaltete Scooter: schützt vor Kratzern und Schmutz im Kofferraum, in der Bahn oder im Flur. Mit Tragegriffen und abnehmbarem Schultergurt.",
    highlights: ["Gepolstert gegen Stöße und Kratzer", "Tragegriffe und abnehmbarer Schultergurt", "Durchgehender Reißverschluss"],
    specs: { "Größe": "XL – für gefaltete Scooter", "Außenmaß": "ca. 110 × 30 × 40 cm", "Material": "Polyester, gepolstert", "Farbe": "Schwarz / Orange" },
    note: "Wichtig: Miss deinen gefalteten Scooter und vergleiche die Maße, bevor du bestellst.",
  },
  {
    id: "tasche-kabel", cat: "tasche", name: "Ladegerät- & Kabeltasche", tagline: "Ladegerät und Kabel geordnet",
    price: 14.9, meta: ["Kompakt"],
    files: ["tasche-kabel-1.svg", "tasche-kabel-2.svg"],
    desc: "Kleine Organizer-Tasche für Ladegerät, Kabel und Kleinteile. Nichts rutscht mehr im Rucksack oder Kofferraum herum.",
    highlights: ["Platz für Ladegerät + Kabel", "Robuster Reißverschluss", "Passt in Rucksack und Scooter-Tasche"],
    specs: { "Maße": "ca. 25 × 12 × 10 cm", "Material": "Polyester", "Farbe": "Schwarz / Orange" },
    note: "Lieferung ohne Ladegerät und Kabel.",
  },
  {
    id: "tasche-rucksack", cat: "tasche", name: "Rucksack 20 L", tagline: "Der Alltagsbegleiter zum Scooter",
    price: 39.9, meta: ["20 Liter", "Laptopfach"],
    files: ["tasche-rucksack-1.svg", "tasche-rucksack-2.svg"],
    desc: "Schlanker 20-Liter-Rucksack für Arbeit, Uni und Ausflug: gepolsterte Träger, Laptopfach und Vordertasche für alles, was schnell griffbereit sein soll.",
    highlights: ["20 Liter Volumen", "Gepolsterte Träger und Rücken", "Laptopfach und Vordertasche"],
    specs: { "Volumen": "20 Liter", "Laptopfach": "bis ca. 15 Zoll", "Material": "Polyester, wasserabweisend", "Farbe": "Schwarz / Orange" },
  },
  {
    id: "merch-shirt", cat: "merch", name: "Logo T-Shirt", tagline: "Klassisch schwarz mit Orange-Print",
    price: 24.9, meta: ["Baumwolle", "S–XXL"], badge: "Neu",
    files: ["merch-shirt-1.svg", "merch-shirt-2.svg"], sizes: SIZES,
    desc: "Das Shop-Shirt in Schwarz: vorn mit Logo, hinten mit großem „RIDE ELECTRIC“-Print in Weiß und Orange.",
    highlights: ["Weiche Baumwolle", "Logo vorn, großer Print hinten", "Unisex-Schnitt"],
    specs: { "Material": "100 % Baumwolle", "Farbe": "Schwarz", "Druck": "Vorn Logo, hinten „RIDE ELECTRIC“", "Schnitt": "Unisex" },
  },
  {
    id: "merch-hoodie", cat: "merch", name: "Hoodie", tagline: "Warm, weich und auffällig",
    price: 54.9, meta: ["2 Farben", "S–XXL"], featured: true,
    files: ["merch-hoodie-1.svg", "merch-hoodie-2.svg"], sizes: SIZES,
    colors: [{ name: "Schwarz", i: 0 }, { name: "Orange", i: 1 }],
    desc: "Kuschliger Kapuzenpullover mit Känguru-Tasche und Kordel in Kontrastfarbe. Wahlweise in Schwarz oder Orange.",
    highlights: ["Kapuze mit Kordel", "Große Känguru-Tasche", "In Schwarz oder Orange"],
    specs: { "Material": "Baumwoll-Mischgewebe, angeraut", "Farben": "Schwarz, Orange", "Schnitt": "Unisex", "Logo": "Brust, gestickt" },
  },
  {
    id: "merch-cap", cat: "merch", name: "Snapback Cap", tagline: "Für jedes Wetter",
    price: 19.9, meta: ["Verstellbar"],
    files: ["merch-cap-1.svg", "merch-cap-2.svg"],
    desc: "Flache Kappe mit orangefarbenem Schirm und Logo-Patch. Die Größe ist über den Snapback-Verschluss einstellbar.",
    highlights: ["Einheitsgröße, verstellbar", "Logo-Patch vorn", "Orangefarbener Schirm"],
    specs: { "Größe": "Einheitsgröße (verstellbar)", "Material": "Baumwolle / Polyester", "Farbe": "Schwarz / Orange" },
  },
  {
    id: "merch-sticker", cat: "merch", name: "Sticker-Set", tagline: "Für Helm, Laptop & Scooter",
    price: 6.9, meta: ["4 Motive", "Wetterfest"],
    files: ["merch-sticker-1.svg", "merch-sticker-2.svg"],
    desc: "Vier wetterfeste Sticker mit Logo und Sprüchen: für Helm, Laptop, Trinkflasche oder den Scooter.",
    highlights: ["4 verschiedene Motive", "Wetter- und UV-beständig", "Rückstandsfrei ablösbar"],
    specs: { "Inhalt": "4 Sticker", "Material": "Vinylfolie, wetterfest", "Größe": "ca. 5–10 cm" },
  },
  {
    id: "merch-flasche", cat: "merch", name: "Trinkflasche 750 ml", tagline: "Edelstahl, doppelwandig",
    price: 16.9, meta: ["750 ml", "2 Farben"],
    files: ["merch-flasche-1.svg", "merch-flasche-2.svg"],
    colors: [{ name: "Schwarz", i: 0 }, { name: "Orange", i: 1 }],
    desc: "Doppelwandige Edelstahlflasche für unterwegs. Hält Getränke lange kalt oder warm und passt in die meisten Getränkehalter.",
    highlights: ["Edelstahl, doppelwandig isoliert", "Auslaufsicherer Schraubverschluss", "In Schwarz oder Orange"],
    specs: { "Volumen": "750 ml", "Material": "Edelstahl", "Farben": "Schwarz, Orange" },
  },
];
EXTRA.forEach((p) => {
  p.tags = [];
  p.gallery = p.files.map((f) => `img/${f}`);
});
PRODUCTS.push(...EXTRA);
