// Produktkatalog.
// ACHTUNG: Preise und technische Daten sind BEISPIELWERTE und müssen vor dem
// Livegang mit den Herstellerangaben bzw. dem Großhändler abgeglichen werden.
const PRODUCTS = [
  {
    id: "g2-pro",
    name: "Kukirin G2 Pro",
    cat: "scooter",
    tagline: "Der Allrounder für Alltag und Wochenende",
    price: 899.0,
    oldPrice: 1049.0,
    badge: "Bestseller",
    color: "#ff6b35",
    desc: "Kräftiger Antrieb, große Luftreifen und ein robustes Fahrwerk – der G2 Pro ist der Einstieg in die Kukirin-Welt.",
    specs: {
      Motor: "800 W (Spitze)",
      Akku: "48 V / 15 Ah",
      Reichweite: "bis ca. 55 km",
      Reifen: "10\" Luftreifen",
      Bremsen: "Scheibenbremsen",
      Gewicht: "ca. 24 kg",
    },
  },
  {
    id: "g3-pro",
    name: "Kukirin G3 Pro",
    cat: "scooter",
    tagline: "Mehr Power, mehr Reichweite",
    price: 1199.0,
    badge: "Neu",
    color: "#2f9bff",
    desc: "Größerer Akku und stärkerer Motor für lange Pendelstrecken und Steigungen.",
    specs: {
      Motor: "1.000 W (Spitze)",
      Akku: "48 V / 20 Ah",
      Reichweite: "bis ca. 75 km",
      Reifen: "10\" Luftreifen",
      Bremsen: "Hydraulische Scheibenbremsen",
      Gewicht: "ca. 28 kg",
    },
  },
  {
    id: "g4",
    name: "Kukirin G4",
    cat: "scooter",
    tagline: "Das Performance-Modell",
    price: 1699.0,
    color: "#9b5cff",
    desc: "Dual-Antrieb und Vollfederung für sportliche Fahrer, die mehr wollen.",
    specs: {
      Motor: "Dual, 2 × 1.000 W (Spitze)",
      Akku: "52 V / 20 Ah",
      Reichweite: "bis ca. 80 km",
      Reifen: "11\" Luftreifen",
      Bremsen: "Hydraulische Scheibenbremsen",
      Gewicht: "ca. 38 kg",
    },
  },
  {
    id: "m5",
    name: "Kukirin M5",
    cat: "scooter",
    tagline: "Kompakt & wendig für die Stadt",
    price: 649.0,
    color: "#22c55e",
    desc: "Leichter, faltbarer City-Scooter für Bahn, Büro und die letzte Meile.",
    specs: {
      Motor: "500 W (Spitze)",
      Akku: "36 V / 10 Ah",
      Reichweite: "bis ca. 35 km",
      Reifen: "9\" Luftreifen",
      Bremsen: "Scheiben- + E-Bremse",
      Gewicht: "ca. 17 kg",
    },
  },
  {
    id: "c1-pro",
    name: "Kukirin C1 Pro",
    cat: "scooter",
    tagline: "Komfort mit Sitz",
    price: 799.0,
    color: "#f5b800",
    desc: "Zum Stehen oder Sitzen – ideal für längere Strecken und entspanntes Fahren.",
    specs: {
      Motor: "600 W (Spitze)",
      Akku: "48 V / 13 Ah",
      Reichweite: "bis ca. 45 km",
      Reifen: "10\" Luftreifen",
      Bremsen: "Scheibenbremsen",
      Gewicht: "ca. 26 kg",
    },
  },
  {
    id: "helm",
    name: "Urban-Helm mit LED-Rücklicht",
    cat: "zubehoer",
    tagline: "Sicherheit zuerst",
    price: 49.9,
    color: "#e5e7eb",
    desc: "Leichter Fahrradhelm mit integriertem LED-Rücklicht und verstellbarer Passform.",
    specs: { Größe: "M / L verstellbar", Beleuchtung: "LED-Rücklicht (USB-C)" },
  },
  {
    id: "schloss",
    name: "Faltschloss 100 cm",
    cat: "zubehoer",
    tagline: "Schutz vor Diebstahl",
    price: 39.9,
    color: "#94a3b8",
    desc: "Robustes Faltschloss aus gehärtetem Stahl, passt dank Halterung an jeden Rahmen.",
    specs: { Länge: "100 cm", Material: "Gehärteter Stahl" },
  },
  {
    id: "ladegeraet",
    name: "Schnellladegerät 48 V",
    cat: "zubehoer",
    tagline: "Doppelt so schnell geladen",
    price: 69.0,
    color: "#ff6b35",
    desc: "Zweit- oder Ersatzladegerät mit höherem Ladestrom für kürzere Ladezeiten.",
    specs: { Spannung: "48 V", Ladestrom: "4 A" },
  },
  {
    id: "reifen",
    name: "Ersatzreifen-Set 10\"",
    cat: "zubehoer",
    tagline: "Frischer Grip",
    price: 59.0,
    color: "#475569",
    desc: "Pannenschutz-Luftreifen inkl. Schlauch – passend für 10\"-Modelle.",
    specs: { Größe: "10\"", Lieferumfang: "Reifen + Schlauch" },
  },
];
